#!/bin/bash

docker build --build-arg PHP_VERSION=7.4 -t vavyskov/php-ssh:7.4-apache-stretch .
docker push vavyskov/php-ssh:7.4-apache-stretch

docker build --build-arg PHP_VERSION=7.3 -t vavyskov/php-ssh:7.3-apache-stretch .
docker push vavyskov/php-ssh:7.3-apache-stretch

docker build --build-arg PHP_VERSION=7.2 -t vavyskov/php-ssh:7.2-apache-stretch .
docker push vavyskov/php-ssh:7.2-apache-stretch
